from django.urls import path
from.import views

urlpatterns = [
    path('employer-dashboard/',views.employer_dashboard,name='employer_dashboard'),
    path('employer-meeting/',views.employer_meeting,name='employer_meeting'),
    path('employee-meeting/',views.employee_meeting,name='employee_meeting'),
    path('employee-work/',views.employee_work,name='employee_work'),
    path('upload-work/',views.upload_work,name='upload_work'),
    path('admin-work/',views.admin_work,name='admin_work'),
    path('employer-work/',views.employer_work,name='employer_work'),
    path('admin-meeting/',views.admin_meeting,name='admin_meeting'),
    path('create-meeting/',views.create_meeting,name='create_meeting'),
    path('get-recent-application-update/', views.get_recent_application_update, name='get_recent_application_update'), 
    path('update-application-reject/', views.update_application_reject, name='update_application_reject'), 
    path('get-payment-details/', views.get_payment_details, name='get_payment_details'), 
    path('get-view-payment-details/', views.get_view_payment_details, name='get_view_payment_details'), 
    path('make-payment/', views.make_payment, name='make_payment'), 
    path('employer-job/',views.employer_job,name='employer_job'),
    path('employer-application/',views.employer_application,name='employer_application'),
    path('employer-application/create-job',views.create_job,name='create_job'),
    path('employee-dashboard/',views.employee_dashboard,name='employee_dashboard'),
    path('employee-job/',views.employee_job,name='employee_job'),
    path('employee-application/',views.employee_application,name='employee_application'),
    path('work-status-update/',views.work_status_update,name='work_status_update'),
    path('work-status-update-dashboard/',views.work_status_update_dashboard,name='work_status_update_dashboard'),
    path('payment-details/',views.payment_details,name='payment_details'),
    path('edit-payment-details/',views.edit_payment_details,name='edit_payment_details'),
    path('edit-payment-details-dashboard/',views.edit_payment_details_dashboard,name='edit_payment_details_dashboard'),
    path('employer-dashboard/cancel-url',views.cancel_url,name='cancel_url'),
    path('admin-dashboard/',views.admin_dashboard,name='admin_dashboard'),
    path('admin-job/',views.admin_job,name='admin_job'),
    path('admin-application/',views.admin_application,name='admin_application'),
    path('get-job-details/', views.get_job_details, name='get_job_details'),
    path('apply-employee-job/', views.apply_employee_job, name='apply_employee_job'), 
    path('get-job-application-details/', views.get_job_application_details, name='get_job_application_details'), 
    path('update-employer-job-details/', views.update_employer_job_details, name='update_employer_job_details'),
    path('download-resume/', views.download_resume, name='download_resume'),
    path('edit-employer-project/',views.edit_employer_project,name="edit_employer_project"),
    path('edit-admin-project/',views.edit_admin_project,name="edit_admin_project"),
    path('update-application-status/', views.update_application_status, name='update_application_status'),
    path('delete-employer-project',views.delete_employer_project,name='delete_employer_project'),
    path('delete-admin-project',views.delete_admin_project,name='delete_admin_project')
]